// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFUFNh6P7nDoqUf1WSmixtWeoR_JlOhwQ',
    appId: '1:985276660532:web:656a288dd554638e360361',
    messagingSenderId: '985276660532',
    projectId: 'zootopia-test',
    authDomain: 'zootopia-test.firebaseapp.com',
    storageBucket: 'zootopia-test.firebasestorage.app',
    measurementId: 'G-9JG65H91TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmWhoKmyOstSuAK-QilToxcar6wuokxk',
    appId: '1:985276660532:android:6ab910e450922935360361',
    messagingSenderId: '985276660532',
    projectId: 'zootopia-test',
    storageBucket: 'zootopia-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6Bf-9hRDHWxtuIEGM3wVTnvk9BFKXR0',
    appId: '1:985276660532:ios:640b1b5167113159360361',
    messagingSenderId: '985276660532',
    projectId: 'zootopia-test',
    storageBucket: 'zootopia-test.firebasestorage.app',
    iosBundleId: 'com.example.zootopiaHospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6Bf-9hRDHWxtuIEGM3wVTnvk9BFKXR0',
    appId: '1:985276660532:ios:640b1b5167113159360361',
    messagingSenderId: '985276660532',
    projectId: 'zootopia-test',
    storageBucket: 'zootopia-test.firebasestorage.app',
    iosBundleId: 'com.example.zootopiaHospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFUFNh6P7nDoqUf1WSmixtWeoR_JlOhwQ',
    appId: '1:985276660532:web:f5e4f53e8b3dbe86360361',
    messagingSenderId: '985276660532',
    projectId: 'zootopia-test',
    authDomain: 'zootopia-test.firebaseapp.com',
    storageBucket: 'zootopia-test.firebasestorage.app',
    measurementId: 'G-1B9JFMM4FW',
  );

}